"""
Build Treasury Data Warehouse
==============================
Loads CSV files generated by treasury_mock_data.py into a DuckDB database.

Run this after generating CSVs:
  python warehouse/treasury_mock_data.py
  python warehouse/build_warehouse.py

The resulting treasury.duckdb file is a portable, zero-config warehouse
that can be queried by the Dash dashboard, Jupyter notebooks, or any
SQL client via DuckDB.
"""

import duckdb
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Paths relative to warehouse/ directory
SCRIPT_DIR = Path(__file__).parent
CSV_DIR = SCRIPT_DIR.parent / "data" / "generated"
DB_PATH = SCRIPT_DIR / "treasury.duckdb"

# CSV files to load (filename → table name mapping)
TABLES = {
    "dim_entity.csv":                   "dim_entity",
    "dim_product.csv":                  "dim_product",
    "dim_date.csv":                     "dim_date",
    "dim_maturity_bucket.csv":          "dim_maturity_bucket",
    "dim_currency.csv":                 "dim_currency",
    "fact_lcr_daily.csv":               "fact_lcr_daily",
    "fact_ftp_daily.csv":               "fact_ftp_daily",
    "fact_balance_sheet_monthly.csv":   "fact_balance_sheet_monthly",
    "fact_liquidity_gap_monthly.csv":   "fact_liquidity_gap_monthly",
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("\n" + "=" * 60)
    print("Treasury Data Warehouse Builder")
    print("=" * 60)
    
    # Check CSV directory exists
    if not CSV_DIR.exists():
        print(f"\n❌ ERROR: CSV directory not found: {CSV_DIR}")
        print("\nRun this first:")
        print("  python warehouse/treasury_mock_data.py")
        sys.exit(1)
    
    # Check for CSV files
    csv_files = list(CSV_DIR.glob("*.csv"))
    if not csv_files:
        print(f"\n❌ ERROR: No CSV files found in {CSV_DIR}")
        print("\nRun this first:")
        print("  python warehouse/treasury_mock_data.py")
        sys.exit(1)
    
    print(f"\nCSV source: {CSV_DIR}")
    print(f"Database target: {DB_PATH}")
    
    # Remove existing database if present
    if DB_PATH.exists():
        print(f"\n⚠️  Removing existing database: {DB_PATH.name}")
        DB_PATH.unlink()
    
    # Connect to DuckDB (creates new file)
    print("\n🔧 Creating new database...")
    con = duckdb.connect(str(DB_PATH))
    
    # Load each CSV as a table
    print("\n📊 Loading tables:")
    print("-" * 60)
    
    total_rows = 0
    loaded_tables = []
    
    for csv_file, table_name in TABLES.items():
        csv_path = CSV_DIR / csv_file
        
        if not csv_path.exists():
            print(f"  ⚠️  {table_name:<40} SKIPPED (CSV not found)")
            continue
        
        try:
            # Load CSV into DuckDB table
            con.execute(f"""
                CREATE TABLE {table_name} AS 
                SELECT * FROM read_csv_auto('{csv_path}')
            """)
            
            # Get row count
            count = con.execute(f"SELECT COUNT(*) FROM {table_name}").fetchone()[0]
            total_rows += count
            loaded_tables.append(table_name)
            
            # Format output with aligned columns
            status = "✓"
            print(f"  {status}  {table_name:<40} {count:>8,} rows")
            
        except Exception as e:
            print(f"  ❌ {table_name:<40} ERROR: {e}")
    
    # Summary
    print("-" * 60)
    print(f"\n✓ Database created successfully")
    print(f"  • {len(loaded_tables)} tables loaded")
    print(f"  • {total_rows:,} total rows")
    print(f"  • Database size: {DB_PATH.stat().st_size / 1024 / 1024:.1f} MB")
    
    # Quick validation query
    print("\n🔍 Validation check:")
    print("-" * 60)
    
    try:
        # Check group LCR latest value
        result = con.execute("""
            SELECT 
                e.entity_name,
                d.date,
                l.scenario,
                l.lcr_ratio_pct
            FROM fact_lcr_daily l
            JOIN dim_entity e ON e.entity_id = l.entity_id
            JOIN dim_date d ON d.date_id = l.date_id
            WHERE l.entity_id = 'EGROUP'
              AND l.scenario = 'Base'
            ORDER BY d.date DESC
            LIMIT 1
        """).fetchone()
        
        if result:
            entity, date, scenario, lcr = result
            print(f"  Latest group LCR: {lcr:.1f}% ({scenario}, {date})")
            print("  ✓ Data looks good")
        else:
            print("  ⚠️  No LCR data found")
            
    except Exception as e:
        print(f"  ❌ Validation error: {e}")
    
    con.close()
    
    print("\n" + "=" * 60)
    print("Done. You can now run:")
    print("  python dashboard/app.py")
    print("=" * 60 + "\n")


if __name__ == "__main__":
    main()
